name: Pull Request Validation

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --no-build --no-restore -c Release --verbosity normal --logger trx --results-directory TestResults
    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: tests
        path: TestResults
      if: ${{ always() }}
