name: Build and publish to nuget

on:
  release:
    types: [created]

jobs:
  buildAndPublish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --no-build --no-restore -c Release --verbosity normal --logger trx --results-directory TestResults
    - name: Build nupkg
      run: dotnet pack --no-build --no-restore -c Release --output nupkgs
    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: tests
        path: TestResults
      if: ${{ always() }}
    - name: Upload nugets
      uses: actions/upload-artifact@v2
      with:
        name: nupkgs
        path: nupkgs
    - name: Upload release assets
      uses: svenstaro/upload-release-action@2.2.1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: nupkgs
        asset_name: nupkgs
        overwrite: true
    # - name: Publish nupkg
